---
title: TITLE HERE
date: "`r Sys.Date()`"
output: 
  html_document:
          code_folding: hide
          code_download: true
          toc: true
          toc_float: true
  github_document:
          html_preview: false
          toc: true
          toc_depth: 3
---

```{r setup, include=T, message = F, warning = F, echo = F}
knitr::opts_chunk$set(
  echo = knitr::is_html_output(),
  fig.align = "center",
  fig.path = "../Figures/markdown/",
  dev = c("png", "pdf"),
  message = FALSE,
  warning = FALSE,
  collapse = T
)

theme_matt = function(base_size = 18,
                      dark_text = "grey20"){
  mid_text <-  monochromeR::generate_palette(dark_text, "go_lighter", n_colours = 5)[2]
  light_text <-  monochromeR::generate_palette(dark_text, "go_lighter", n_colours = 5)[3]
  
  ggpubr::theme_pubr(base_family="sans") %+replace% 
    theme(
      panel.background  = element_rect(fill="transparent", colour=NA), 
      plot.background = element_rect(fill="transparent", colour=NA), 
      legend.background = element_rect(fill="transparent", colour=NA),
      legend.key = element_rect(fill="transparent", colour=NA),
      text = element_text(colour = mid_text, lineheight = 1.1),
      title = element_text(size = base_size * 1.5,
                           colour = dark_text),
      axis.text = element_text(size = base_size,
                               colour = mid_text),
      axis.title.x = element_text(size = base_size * 1.2,
                                  margin = unit(c(3, 0, 0, 0), "mm")),
      axis.title.y = element_text(size = base_size * 1.2,
                                  margin = unit(c(0, 5, 0, 0), "mm"), 
                                  angle = 90),
      legend.text = element_text(size=base_size * 0.9),
      legend.title = element_text(size = base_size * 0.9, 
                                  face = "bold"),
      plot.margin = margin(0.25, 0.25, 0.25, 0.25,"cm")
    )
}

theme_matt_facets = function(base_size = 18,
                             dark_text = "grey20"){
  mid_text <-  monochromeR::generate_palette(dark_text, "go_lighter", n_colours = 5)[2]
  light_text <-  monochromeR::generate_palette(dark_text, "go_lighter", n_colours = 5)[3]
  
  theme_bw(base_family="sans") %+replace% 
    theme(
      panel.grid = element_blank(),
      panel.background  = element_rect(fill="transparent", colour=NA), 
      plot.background = element_rect(fill="transparent", colour=NA), 
      legend.background = element_rect(fill="transparent", colour=NA),
      legend.key = element_rect(fill="transparent", colour=NA),
      text = element_text(colour = mid_text, lineheight = 1.1),
      strip.text.x = element_text(size = base_size),
      title = element_text(size = base_size * 1.5,
                           colour = dark_text),
      axis.text = element_text(size = base_size,
                               colour = mid_text),
      axis.title.x = element_text(size = base_size * 1.2,
                                  margin = unit(c(3, 0, 0, 0), "mm")),
      axis.title.y = element_text(size = base_size * 1.2,
                                  margin = unit(c(0, 5, 0, 0), "mm"), 
                                  angle = 90),
      legend.text = element_text(size=base_size * 0.9),
      legend.title = element_text(size = base_size * 0.9, 
                                  face = "bold"),
      plot.margin = margin(0.25, 0.25, 0.25, 0.25,"cm")
    )
}
```

## Boston Harbor Seasonality 

```{r}

bharb_temps %>% 
  mutate(month = lubridate::month(date),
         year = lubridate::year(date)) %>% 
  ggplot(aes(x = month, y = mean_temp, group = year, colour = year)) + 
  geom_line(alpha = 0.5) + 
  scale_x_continuous(breaks = c(1:12)) + 
  scale_colour_viridis_c(option = "G") + 
  labs(x = "Month", 
       y = "Mean Temp. (°C)") + 
  theme_matt() + 
  theme(legend.position = "right")

bharb_temps %>% 
  mutate(month = lubridate::month(date),
         year = lubridate::year(date)) %>% 
  filter(month %in% c(3, 8)) %>% 
  mutate(month = if_else(month == 3, "March", "August"),
         month = fct_relevel(month, "March", "August")) %>% 
  ggplot(aes(x = year, y = mean_temp)) + 
  facet_wrap(.~month, scales = "free_y") + 
  geom_line() + 
  geom_smooth() + 
  labs(x = "Year", 
       y = "Mean Temp. (°C)") + 
  theme_matt_facets()

```


## CTmax Data

```{r}

trait_data %>% 
  mutate(date = as_date(collection_datetime)) %>% 
  ggplot(aes(x = date, y = ctmax, colour = species)) + 
  geom_point(position = position_dodge(width = 0.1)) + 
  theme_matt() + 
  theme(legend.position = "right")

```

```{r}

trait_data %>% 
ggplot(aes(x = species, y = ctmax)) + 
  geom_boxplot() + 
  geom_point() + 
  theme_matt_facets() + 
  theme(axis.text.x = element_text(angle = 300, hjust = 0, vjust = 0.5))

```

```{r}

trait_data %>% 
  group_by(species, sex) %>% 
  summarise(mean_ctmax = mean(ctmax, na.rm = T), 
            ctmax_se = sd(ctmax) / sqrt(n())) %>% 
ggplot(aes(x = sex, y = mean_ctmax, group = species)) + 
  facet_wrap(species~.) + 
  geom_line(linewidth = 1) + 
  geom_errorbar(aes(ymin = mean_ctmax - ctmax_se, ymax = mean_ctmax + ctmax_se),
                width = 0.2, linewidth = 1) + 
  geom_point(size = 2) + 
  theme_matt_facets()

```

